### PR TITLE
Fix #1: No effect on form builder in 4.13 (add on loadFormField)

### LINKED ISSUE #1: Hook getAttributesFromDca not called in Contao 4.13.30
I composer-required the module (1.2.1) in a Contao 4.13 (which uses Eclipse Theme, if that is relevant).

Form fields are called "email" and "name" so I expect the autocomplete to be added automatically.

The forms are created using the standard Contao form builder.

During debugging I found that \Contao\Widget::getAttributesFromDca seems to be never called so that's why the hook is not working.

Still trying to investigate .. maybe something changed with Contao 4.13 here.

Any hints are still welcome :-)

### PR DESCRIPTION
**Pull request by amenk**

### CODE REVIEW

**Comment by koertho** [comment]
Hi, thanks for your contribution, that's a good enhancements. I think we should rename the class, since it is not only a getAttributesFromDca listener anymore. Something like "AddAutocompleteValuesListener" or so.

**Comment by amenk** [comment]
Thanks for the feedback, I will rename it.

**Comment by amenk** [comment]
ready :)

**Comment by amenk** [comment]
let me know if there are more comments, otherwise a merge & new release would be great so we can easily `composer update` our project.

**Review by koertho — APPROVED** [review]

**Comment by koertho** [comment]
Thank you @amenk !

**Pull request merged**
